name: foobar2000
title: foobar2000 (WINE)
summary: foobar2000 is an advanced freeware audio player.
description: |
 Features
   *Supported audio formats are MP3, MP4, AAC, CD Audio, WMA, Vorbis, Opus, FLAC, WavPack, WAV, AIFF, Musepack, Speex, AU, SND... and more with additional components.
   *Gapless playback.
   *Easily customizable user interface layout.
   *Advanced tagging capabilities.
   *Support for ripping Audio CDs as well as transcoding all supported audio formats using the Converter component.
   *Full ReplayGain support.
   *Customizable keyboard shortcuts.
   *Open component architecture allowing third-party developers to extend functionality of the player.
adopt-info: foobar2000

confinement: strict
grade: stable
architectures:
  - build-on: arm64
base: core20
compression: lzo

plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-devel-core20

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml="  # Prevent pop-ups about Wine Mono and Wine Gecko
  WINEARCH: "win32"
  TRICKS: "wmp9 vcrun2017"
  RUN_EXE: "$SNAP_USER_DATA/foobar2000/foobar2000.exe"
  SOMMELIER_KEEP_CWD: "1"  # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1"  # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1"  # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

apps:
  foobar2000:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier run-exe
    plugs:
      - audio-playback
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
      - optical-drive
    desktop: usr/share/applications/foobar2000.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  enable-armhf:
    plugin: nil
    override-build: |
      snapcraftctl build
      dpkg --add-architecture armhf
      apt update

  ppa:
    plugin: nil
    override-build: |
      snapcraftctl build
      wget https://ryanfortner.github.io/box86-debs/box86.list -O /etc/apt/sources.list.d/box86.list
      wget -qO- https://ryanfortner.github.io/box86-debs/KEY.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/box86-debs-archive-keyring.gpg
      apt update
    build-packages:
      - wget
    stage-packages:
      - box86-arm-generic
 
  foobar2000:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget http://www.foobar2000.org/download -q -S -O - 2>&1 | grep foobar2000_v | awk '{print $3}'|sed '2,3d;s|v||;s|</a><br/>||;s|</a>||')
      snapcraftctl set-version "$ver"
      ./dl_f2k
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - sommelier
    build-packages: [wget]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "tmp-core20"

  # This reverts changes from https://github.com/snapcore/snapcraft/pull/3586
  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
